project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Hello I'm João"
  site-url: https://joao.granja-correia.eu
  repo-url: https://github.com/joaojcorreia/joaojcorreia.github.io

  page-footer:
    left: "&copy; Copyright 2023, João Granja-Correia"
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."

  navbar:
    left:
      - href: index.qmd
        text: Home

      - href: projects/index.qmd
        text: Projects
        
      - href: blog/blog.qmd
        text: Blog

      - href: about.qmd
        text: About

format:
  html:
    theme: [simplex, styles.scss]
    mainfont: "Atkinson Hyperlegible"





